server:
  port: 8080
  servlet:
    context-path: /vendas-api

springdoc:
  swagger-ui:
    path: /documentacao
  api-docs:
    path: /docs

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27021/vendas?replicaSet=rs0